---
- name: MariaDB server is running
  hosts: database_prod
  vars:
    maria_packages:
      - mariadb-server
      - python3-PyMySQL
  tasks:
    - name: Install MariaDB Packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ maria_packages }}"
      when: ansible_distribution == 'CentOS'

    - name: Start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: true
