---
- name: Resotre
  hosts: all
  vars:
    pkg_fw: firewalld
    pkg_http: httpd
    pkg_https: mod_ssl
    conf_httpd_src: files/httpd.conf
    conf_httpd_dest: /etc/httpd/conf/httpd.conf
    htaccess_src: files/.htaccess 
    htaccess_dest:  "{{ web_root }}/.htaccess"
    secrets_dir: /etc/httpd/secrets
    secrets_src: files/htpasswd
    secrets_dest: "{{ secrets_dir }}/htpasswd"
    web_root: /var/www/html

    svc_fw: firewalld
    svc_web: httpd
    fw_http: http
    fw_https: https
  tasks:
    - name: Close the port firewall - {{ fw_http }}, {{ fw_https }}
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      ignore_errors: yes
      loop:
        - "{{ fw_http }}"
        - "{{ fw_https }}"

    - name: Stop the service with service module - {{ svc_fw }}, {{ svc_http }}
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      ignore_errors: yes
      loop:
        - "{{ svc_fw }}"
        - "{{ svc_web }}"

    - name: Remove the file
      file:
        path: "{{ web_root }}/index.html/files/index.html"
        state: absent

    - name: Remove the file 
      file:
        path: "{{ secrets_dir }}"
        state: absent

    - name: Remove the file 
      file:
        path: "{{ secrets_dest }}"
        state: absent

    - name: Remove the file 
      file:
        path: files/.htaccess
        state: absent

    - name: Remove the file 
      file:
        path: "{{ conf_httpd_dest }}"
        state: absent

    - name: Remove the Packages - {{ pkg_http }}, {{ pkg_https }}, {{ pkg_fw }}
      yum:
        name:
          - "{{ pkg_fw }}"
          - "{{ pkg_http }}"
          - "{{ pkg_https }}"
        state: absent