---
- name: Make Files
  hosts: dev
  tasks:
    - name: Make Files - /etc/myhosts
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/myhosts
        owner: root
        group: root
        mode: '0644'