---
- name: Add Users
  hosts: dev, test, prod
  vars_files:
    - userlist.yml
    - pw.yml
  tasks:
    - name: Add Users - user1
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
        password: "{{ pw_dev | password_hash('sha512') }}"
        state: present
      loop:
        "{{ users }}"
      when:
        - ( inventory_hostname in groups.dev) or (inventory_hostname in groups.test)
        - ( item.username == "developer")

    - name: Add Users - user2
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
        password: "{{ pw_mgr | password_hash('sha512') }}"
        state: present
      loop:
        "{{ users }}"
      when:
        - ( inventory_hostname in groups.dev) or (inventory_hostname in groups.test)
        - ( item.username == "mgr")