---
- name: Install_facts.yml
  hosts: web1
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: files/custom.facts
  tasks:
    - name: Create the Remote directory
      file:
        path: "{{ remote_dir }}"
        state: directory
        mode: '0755'

    - name: Copy Fact files
      copy:
        src:  "{{ facts_file }}"
        dest: "{{ remote_dir }}"



