---
- name: Configure webserver
  hosts: webserver
  tasks:
    - name: Install Packages
      yum: 
        name: "{{ ansible_local.custom.general.package }}"
        state: latest
    
    - name: Start Service
      service:
        name: "{{ ansible_local.custom.general.service }}"
        state: "{{ ansible_local.custom.general.state }}"