---
- name: Time Synchronization
  hosts:  datacenters

  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name:
      ansible.builtin.timezone:
        name: "{{ host_timezone }}"
      notify: restart chronyd

  handlers:
    - name: restart chronyd
      ansible.builtin.service:
        name: chronyd
        state: restarted