---
- name: Configure web server
  hosts: webservers

  tasks:
    - name: Include the environment task file and set the variables
      include_tasks: tasks/environment.yml
      vars:
        package:
          - httpd
          - mod_ssl
        service:
          - httpd

    - name: Import the placeholder task file and set the variables
      import_tasks: tasks/placeholder.yml
      vars:
        indexfile: /var/www/html/index.html
        motdfile: /etc/motd

    - name: Include tasks - tasks/firewall.yml
      ansible.builtin.include_tasks: 
        tasks/firewall.yml
      vars:
        firewall_pkg: firewalld
        firewall_svc: firewalld
        rule:
          - http
          - https

    
- name: Import test play file and set the variable
  import_playbook: plays/test.yml
  vars:
    url: "http://ansible1.example.com"