---
- name: Mail
  hosts: all
  gather_facts: yes
  tasks:
    - name: Include Configure_main.yml
      ansible.builtin.include_tasks:
        configure_mail.yml
      when: inventory_hostname in groups['mailservers']

  handlers:
    - name: start_postfix
      ansible.builtin.service:
        name: postfix
        state: started

    - name: start_dovecot
      ansible.builtin.service:
        name: dovecot
        state: started

    - name: restart_postfix
      ansible.builtin.service:
        name: postfix
        state: restarted