---
- name: Tag
  hosts: webservers
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_config_src_path_small: http://ansible.example.com/my.cnf.small
    db_config_src_path_large: http://ansible.example.com/my.cnf.large
    db_config_path: /etc/my.cnf
    svc_db: mariadb
  gather_facts: true
  tasks:
    - name: DB 작업 수행
      ansible.builtin.include_tasks: prepare_db.yml
      when: inventory_hostname in group['databases']
    
  handlers:
    - name: start_db
      service:
        name: "{{ svc_db }}"
        state: started

    - name: restart_db
      ansible.builtin.service:
        name: "{{ svc_db }}"
        state: restarted



      